id: IE4EC34A8
ocr_import_info:
  bdrc_scan_id: W1KG17114
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-03-08 19:42:37.408694
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17114
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17114
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན།
  languages:
  - bo
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
bases:
  I1KG17128:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17128
      total_pages: 540
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG17128.txt
    order: 1
  I1KG17129:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17129
      total_pages: 356
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I1KG17129.txt
    order: 2
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
